### ISSUE TITLE
Isn't working with KODI anymore?

### ISSUE THREAD

**Issue by bromix** [powlo/script.module.pydevd#1]
Hi,

I used your addon a lot with Gotham and JetBrains PyCharm. Now I updated to KODI and I get always the exception, that the import of the moduel 'pydevd' wasn't found.

Somehow the module isn't on the path anymore.
Am I missing something or is this a problem with KODI?

If you need more information, please tell.

regards
bromix

**Comment by powlo** [comment]
~~It looks as though the Kodi team has knobbled the extension point paramneter.~~

~~<extension point="xbmc.python.module" library="lib"/>~~

~~Probably needs to change to something else. Maybe naming all the files under lib? Seems a bit tiresome.~~

~~http://kodi.wiki/view/Addon.xml#xbmc.python.pluginsource~~
~~http://kodi.wiki/view/Plugin_sources~~

Nonsense.

**Comment by powlo** [comment]
So I tested it with Kodi and it works fine. Maybe make sure that you declare pydevd as a <requires> in your addon.xml.

I think all a <requires> achieves (other than fetching from repos on install) is to put the module on the sys.path. So if you don't declare a <requires> yet have another module that does, then your module with the undeclared dependency can appear to work.

**Comment by bromix** [comment]
Doesn't work for me. I try something else :) but thanks for your time.

**Comment by powlo** [comment]
```
print sys.path
```

might offer some clues. Check that the path to the lib directory of script.module.pydevd is in there.

**Comment by bromix** [comment]
I validate this after work :) thanks for the hint.
