### ISSUE TITLE
No Breakpoints possible, unless file pydevd_file_utils.py is changed

### ISSUE THREAD

**Issue by SchapplM** [powlo/script.module.pydevd#2]
I needed to fix the file pydevd_file_utils.py according to http://kodi.wiki/view/HOW-TO:Debug_Python_Scripts_with_Eclipse#Modify_PyDev_source_in_order_to_support_XBMC_paths to be able to set breakpoints debugging a xbmc addon.

My setup:
Ubuntu 14.04.1
Eclipse 3.8.1 (from Ubuntu sources)
PyDev for Eclipse 3.9.0.201411111611
Kodi 14,0

**Comment by powlo** [comment]
I never had any problems with inserting breakpoints, but maybe that's because I was never inserting them in XBMC paths.

Can you submit a test to prove the point?

**Comment by SchapplM** [comment]
I am currently only using eclipse and pydev to debug the addon I am developping.
The following steps should reproduce the problem:
1.) Install addon from zip in xbmc (http://xbmc-addon-service-watchedlist.googlecode.com/archive/testing.zip)
2.) activate debug mode (pay attention to the debug server port). https://code.google.com/p/xbmc-addon-service-watchedlist/source/browse/manual.py#9
3.) Add the addon folder to a pydev project in eclipse (http://kodi.wiki/view/HOW-TO:Debug_Python_Scripts_with_Eclipse#Import_File_System)
4.) Start debug server
5.) manually start the addon in Kodi/XBMC
6.) the python script should stop at the line, where the main class is created (https://code.google.com/p/xbmc-addon-service-watchedlist/source/browse/manual.py#26). Manually stepping forward and stepping into worked for me. Continuing until next breakpoint (hotkey F8) did not stop the script  there.

I really had trouble setting up eclipse for debugging in ubuntu so I really appreciate your pydevd-addon :+1:

**Comment by powlo** [comment]
OK I just tried this out with buggalo and your service.watchlist, using Kodi 14.0 on Ubuntu.

I was able to get debugging working fine, including breakpoints.

Some points to note:

You shouldn't need modify any source files in the PyDev source.

You shouldn't need to set the machine and port if you're debugging locally. I just use

```
pydevd.settrace(stdoutToServer=True, stderrToServer=True)
```

There's possibly a disconnect in your __remotedebug__ setting. I'm assuming this is supposed to come from a setting, but its not coded to so it'll just sit there being false as far as I can tell. There's a getSetting() method available to addons that you can use.

Here's a screengrab of me debugging: ![Screengrab](http://i61.tinypic.com/1zlzq5u.png)

**Comment by SchapplM** [comment]
Thanks for your input.
Perhaps it was some other reason it did not work at the first time.
I manually change the setting in the code when I am debugging.
